### ISSUE TITLE
format of colors not clear in usage

### ISSUE THREAD

**Issue by simsong** [JessThrysoee/xtermcontrol#11]
The usage message uses the phrase `COLOR` but it doesn't make it clear if `COLOR` is a numbered color 0-255 or if it can be an RGB sequence.  From [this page](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Operating-System-Commands), it appears that it can be either?

**Comment by JessThrysoee** [comment]
They are explained in the 'COLOR NAMES' section of the manpage, i.e. `man xtermcontrol`.

The same text is available on https://thrysoee.dk/xtermcontrol/#color_names with a link to https://www.x.org/releases/X11R7.7/doc/man/man7/X.7.xhtml#heading11 if you don't have the manpages installed.

I'll add a `See 'man xtermcontrol' for more information` at the bottom of the usage message.

**Comment by simsong** [comment]
From a usability point of view, it would be useful to have them explained in the usage as well.
