### ISSUE TITLE
Build with aclocal 1.15

### ISSUE THREAD

**Issue by gfiorav** [JessThrysoee/xtermcontrol#12]
Hi, thanks for creating this tool.

I've noticed that it requires `aclocal-1.16` (part of `automake-1.16`) but it's currently in testing and not fully released (at least in Debian). Is there any chance this build would work with `automake-1.15`?

Thanks.

**Comment by JessThrysoee** [comment]
Hi @gfiorav.

Are you trying to build, i.e. does './.configure && make' fail?

Or are you regenerating the autotools scripts? Does  './bootstrap.sh' or 'autoconf -fi' fail?

**Comment by gfiorav** [comment]
Hey, thanks for the quick reply. It's failing on the `make` step. I've tried to reproduce it, but since I installed aclocal 16 from the debian testing repo I can't. I've tried uninstalling it and `distclean` but it now works. Not sure what I did wrong.

Thanks anyway!
