### ISSUE TITLE
 How to configure font size

### ISSUE THREAD

**Issue by junyu-wu** [JessThrysoee/xtermcontrol#14]
--font is config font. how to change font size?

**Comment by clort81** [comment]
With traditional X11 fonts, the font names specify a size.
e.g.
5x8
6x10
6x12
6x13
6x13
6x13bold
6x9
7x13
7x13bold
-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-10
-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-11
-misc-fixed-medium-r-semicondensed--13-120-75-75-c-60-iso8859-13

The command _xlsfonts_ shows them

**Comment by JessThrysoee** [comment]
I think @clort81 has answered this, and otherwise I'll refer to https://thrysoee.dk/xtermcontrol/#font_names

**Comment by JessThrysoee** [comment]
I think @clort81 has answered this, and otherwise I'll refer to https://thrysoee.dk/xtermcontrol/#font_names
