### ISSUE TITLE
tty_read() changes break on cygwin

### ISSUE THREAD

**Issue by nemws1** [JessThrysoee/xtermcontrol#6]
On Cygwin, with the current version of xtermcontrol, when calling any of the --get-* options, I always get:

  read: Resource temporarily unavailable

But it used to work (and I knew this).  I traced the issue back to the changes made for tty_read() on commit e04115e.  The code previous to this works on cygwin.

With a little more debugging, I've found that for some reason, on Cygwin, read(TTY_FILENO, p, 1) returns a -1 instead of a zero when there is no more data to read (see attachment).  If I change line 935 of xtermcontrol.c from:

  else if (n == 0)

to:

  else if (n == 0 || n == -1)

Then this works for me, but obviously this is a kludge.  I'd be happy to debug/try any suggestions you have that would be more universally compliant.

Attaching patch (w/ debug info) and the output from 'xtermcontrol --get-geometry'.

[tty_read.patch.txt](https://github.com/JessThrysoee/xtermcontrol/files/59523/tty_read.patch.txt)
[tty_read_debug-out.txt](https://github.com/JessThrysoee/xtermcontrol/files/59524/tty_read_debug-out.txt)

**Comment by JessThrysoee** [comment]
Does 991d505 fix this issue?

**Comment by nemws1** [comment]
Unfortunately, this causes xtermcontrol to hang (infinite loop). :(

Right after the read() call I added:

fprintf(stderr, "EAGAIN: %d - errno: %d - n: %d\n", EAGAIN, errno, n);

And I get:

$ ./xtermcontrol --get-geometry
EAGAIN: 11 - errno: 0 - n: 1
EAGAIN: 11 - errno: 0 - n: 1
EAGAIN: 11 - errno: 0 - n: 1
EAGAIN: 11 - errno: 0 - n: 1
EAGAIN: 11 - errno: 0 - n: 1
EAGAIN: 11 - errno: 0 - n: 1
EAGAIN: 11 - errno: 0 - n: 1
EAGAIN: 11 - errno: 0 - n: 1
EAGAIN: 11 - errno: 0 - n: 1
EAGAIN: 11 - errno: 0 - n: 1
EAGAIN: 11 - errno: 11 - n: -1
EAGAIN: 11 - errno: 11 - n: -1
....(repeats)

**Comment by JessThrysoee** [comment]
OK, so apparently this is POSIX compliant behaviour. Please try 77b510e

**Comment by nemws1** [comment]
Yes, this one works perfectly. :)

**Comment by JessThrysoee** [comment]
I have merged and created a xtermcontrol-3.3 release.

Thank you for taking the time to track this problem down.

**Comment by nemws1** [comment]
Dank je! :)
