### ISSUE TITLE
--bg and --fg are inverted

### ISSUE THREAD

**Issue by exebook** [JessThrysoee/xtermcontrol#9]
Just cloned, built and tested it. The first command I tried is to change background and it changed foreground. Then I tried foreground and it changed background.

**Comment by exebook** [comment]
This was the dafault xterm from apt-get on Ubuntu. I just built the official xterm from https://invisible-island.net/xterm/#download and it works as expected. Probably should fire a bug somewhere else!

**Comment by JessThrysoee** [comment]
I am unable to reproduce your findings on a newly installed Ubuntu Desktop system:

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"

$ sudo apt install xterm xtermcontrol

$ xtermcontrol --version
xtermcontrol 3.3

$ xterm -v
XTerm(330)
```

I have also tried downloading and compiling the latest xtermcontrol version 3.6.

Please provide more details of the versions of OS and applications, and if you e.g. have a customized ~/.Xdefaults resource file.

**Comment by exebook** [comment]
Thanks for answering!
You were right, I was starting xterm with the script that added some extra options. If I start xterm without options the behavior is correct.

So since my options caused this inversion, it is interesting to know which one?

```shell
xterm -geometry 116x30 \
        -ls -xrm "XTerm*selectToClipboard: true" \
        -fs 10.5 \
        -fa "$TERMFONT" \
        -fg "#f0f7ed" \
        -bg "#000000" \
        -b 15 \
        -T _xterm_new_window \
        -ms "#ff0000" +dc -r -rv \
        -e "xseticon -name _xterm_new_window $TERMICON; bash"
```

**Comment by exebook** [comment]
Ok, it's 
```
     -r This option indicates that reverse video should be simulated by swapping the foreground and
               background colors.
```

I probably misunderstood the effect.
